# ./.tmuxinator.yml

name: FarmBot 
root: ~/

pre_window: export PS1=" \[$(tput sgr0)\]\[$(tput bold)\]\[\033[38;5;45m\]>>>\[$(tput sgr0)\] \[$(tput sgr0)\]"


startup_window: Hardware
# startup_pane: 0

windows:
  - Hardware: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 launch arduino_system hardware.launch.py 
  - EKF: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 launch farmbot_ekf ekf.launch.py 
  - Carto: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; sleep 3; ros2 launch farmbot_carto mapping.launch.py
  - Debug: 
      root: ~/
      panes:
        - clear; source ~/.bashrc;
