twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel_smoother_to_collision #cmd_vel_collision_to_twist # rviz goal , this come from /goal_pose
        timeout: 1.0
        priority: 110
      behavior:
        topic: cmd_vel_bh_to_twist # behavior server and joystick from behavior server
        timeout: 1.0
        priority: 100
      joystick:
        topic: cmd_vel # keyboard
        timeout: 1.0
        priority: 100
      web:
        topic: cmd_vel_web_to_twist # flutter web
        timeout: 1.0
        priority: 100
      bhserver:
        topic: cmd_vel_bhserver # qt
        timeout: 1.0
        priority: 100
