### ekf config file ###
ekf_localization_node:
    ros__parameters:
        use_sim_time: False
        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: map

        frequency: 30.0
        sensor_timeout: 0.1

        two_d_mode: true

        publish_tf: false
        # publish_acceleration: false
        # publish_velocity: false
        # publish_odometry: false
        # publish_pose: true
        odom0 : /ekf_odom_local
        odom0_config: [true,  true,  false,
                      false, false, false,
                      false, false, false,
                      false, false, true,
                      false, false, false]
        imu0: imu/out
        imu0_config: [false, false, false,  # Position (x, y, z)
                      false, false,  true,   # Orientation (roll, pitch, yaw)
                      false, false, false,  # Linear velocity (x, y, z)
                      false, false, false,   # Linear acceleration (x, y, z)
                      false, false, false]   # Angular velocity (x, y, z)
        imu0_nodelay: false
        imu0_differential: false
        imu0_relative: true
        imu0_queue_size: 5     # ROM EDIT original 5
        imu0_pose_rejection_threshold: 0.8                 # Note the difference in parameter names
        imu0_twist_rejection_threshold: 0.8                #
        imu0_linear_acceleration_rejection_threshold: 0.8  #


        pose0:
          topic: "/tf"
          target_frame: "map"
          source_frame: "odom"
          data_source: "tf"
          differential: false
          relative: false
          xyz_stddev: 0.01
          rpy_stddev: 0.01
